### ISSUE TITLE
nv-nsight-cu-cli is not profiling anything

### ISSUE THREAD

**Issue by BDHU** [NVIDIA/cuda-samples#10]
Whenever I use nv-nsight-cu-cli to profile anything it simply throws an error "==PROF== No kernels were profiled". What is the correct way to use nsight compute?

**Comment by mdoijade** [comment]
@BDHU You can ask about issues related to nsight compute, on its developer forum -https://devtalk.nvidia.com/default/board/327/nsight-compute-/
You can provide complete details about your setup (that is cuda toolkit used, GPU, nvidia driver version, etc) on that forum to get help.

**Comment by BDHU** [comment]
It seems GP100 is not supported at this moment. But any idea why?
