### ISSUE TITLE
Loading samples failed in VS2022. Here is the probably solution

### ISSUE THREAD

**Issue by Hashiao** [NVIDIA/cuda-samples#157]
CUDA version 11.8
NVIDIA Driver version 522.06
When open "Samples_VS2022.sln" downloaded from git, all projects can't be loaded normally. 
You may try to modify the CUDA version information in *.vcxproj, and then reload projects.
For example

`<Import Project="$(CUDAPropsPath)\CUDA 12.0.props" />`

should be modified to 

`<Import Project="$(CUDAPropsPath)\CUDA 11.8.props" />`

`<Import Project="$(CUDAPropsPath)\CUDA 12.0.targets" />`

should be modified to 

`<Import Project="$(CUDAPropsPath)\CUDA 11.8.targets" />`

Remember to reload projects. Now compile and run the sample~

**Comment by xiaoleitongxue** [comment]
I met same problem, and I solved this by replacing all "12.0" to "11.8" using vscode. and Then I open project in vs 2022, It worked.

**Comment by semicolonTransistor** [comment]
I wrote this short Python script to automatically find and replace all the incorrect versions. Run it in the root directory of the repo and it should find and replace all versions in all vcxproj files.

```python
import glob
import re


TARGET_VERSION = "11.8"


def main():
    for file_name in glob.glob("Samples/**/*.vcxproj", recursive=True):
        with open(file_name, "rb") as file:
            content = file.read().decode("utf-8")
            
        content = re.sub(r"CUDA\s*\d+.\d+.props", f"CUDA {TARGET_VERSION}.props", content)
        content = re.sub(r"CUDA\s*\d+.\d+.targets", f"CUDA {TARGET_VERSION}.targets",content)

        with open(file_name, "wb") as file:
            file.write(content.encode("utf-8"))


if __name__ == "__main__":
    main()
```

**Comment by Hashiao** [comment]
> I wrote this short Python script to automatically find and replace all the incorrect versions. Run it in the root directory of the repo and it should find and replace all versions in all vcxproj files.
> 
> ```python
> import glob
> import re
> 
> 
> TARGET_VERSION = "11.8"
> 
> 
> def main():
>     for file_name in glob.glob("Samples/**/*.vcxproj", recursive=True):
>         with open(file_name, "rb") as file:
>             content = file.read().decode("utf-8")
>             
>         content = re.sub(r"CUDA\s*\d+.\d+.props", f"CUDA {TARGET_VERSION}.props", content)
>         content = re.sub(r"CUDA\s*\d+.\d+.targets", f"CUDA {TARGET_VERSION}.targets",content)
> 
>         with open(file_name, "wb") as file:
>             file.write(content.encode("utf-8"))
> 
> 
> if __name__ == "__main__":
>     main()
> ```

6

> I wrote this short Python script to automatically find and replace all the incorrect versions. Run it in the root directory of the repo and it should find and replace all versions in all vcxproj files.
> 
> ```python
> import glob
> import re
> 
> 
> TARGET_VERSION = "11.8"
> 
> 
> def main():
>     for file_name in glob.glob("Samples/**/*.vcxproj", recursive=True):
>         with open(file_name, "rb") as file:
>             content = file.read().decode("utf-8")
>             
>         content = re.sub(r"CUDA\s*\d+.\d+.props", f"CUDA {TARGET_VERSION}.props", content)
>         content = re.sub(r"CUDA\s*\d+.\d+.targets", f"CUDA {TARGET_VERSION}.targets",content)
> 
>         with open(file_name, "wb") as file:
>             file.write(content.encode("utf-8"))
> 
> 
> if __name__ == "__main__":
>     main()
> ```

neat and clean

**Comment by Hashiao** [comment]
the description page of cuda samples said that the version is 12.0. but so far I guess 12.0 hasn’t been released yet. Nvidia may makes such cute mistake,amazing

**Comment by rnertney** [comment]
The props files were indeed incorrectly set. That should be the only change required, however both master and tag v11.8 should be correct now
