### ISSUE TITLE
 NVJPEG_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by gangdelian** [NVIDIA/cuda-samples#20]
Hi,
I use nvjpeg， found if the image size smaller than 2*256，like 1x1，the nvJPEG_encoder sample will recieve the following error：
CUDA error at d:\cppworkspace\cuda-samples\samples\nvjpeg_encoder\nvjpeg_encoder.cpp:200 code=6(NVJPEG_STATUS_EXECUTION_FAILED) "nvjpegEncodeYUV(nvjpeg_handle, encoder_state, encode_params, &imgdesc, subsampling, widths[0], heights[0], NULL)"

and the strange things is， the 1x1 image must be the first compressed，will trigger the bug，if the image is compressed after a big image like 480x640，the bug will dispear.
can someone help me？

**Comment by maheshkha** [comment]
Hi Gangdelian,
Can you change this line in nvjpeg_encoder.cpp: 484
`checkCudaErrors(nvjpegEncoderParamsSetOptimizedHuffman(encode_params, 1, NULL));`
with this line
`checkCudaErrors(nvjpegEncoderParamsSetOptimizedHuffman(encode_params, 0, NULL));`

Hope this will fix your issue.

**Comment by gangdelian** [comment]
> Hi Gangdelian,
> Can you change this line in nvjpeg_encoder.cpp: 484
> `checkCudaErrors(nvjpegEncoderParamsSetOptimizedHuffman(encode_params, 1, NULL));`
> with this line
> `checkCudaErrors(nvjpegEncoderParamsSetOptimizedHuffman(encode_params, 0, NULL));`
> 
> Hope this will fix your issue.

Thanks, It works.
