### ISSUE TITLE
Out-of-bounds read in reduction_kernel.cu variant reduce6 for array size 1

### ISSUE THREAD

**Issue by emjotde** [NVIDIA/cuda-samples#21]
Hi,
your kernel reduce6 from the reduction example does an out-of-bounds read for trivial input size 1 here:

https://github.com/NVIDIA/cuda-samples/blob/6be514679b201c8a0f0cda050bc7c01c8cda32ec/Samples/reduction/reduction_kernel.cu#L357

This is caused by determining that size 1 is also a power of 2 here:

https://github.com/NVIDIA/cuda-samples/blob/6be514679b201c8a0f0cda050bc7c01c8cda32ec/Samples/reduction/reduction.cpp#L88

but incorrectly assuming that we can increase by `blockSize` (==1).

Best,
Marcin

**Comment by mdoijade** [comment]
@emjotde samples sources are expected to be used as is, modified source bugs are expected. closing this issue.

**Comment by emjotde** [comment]
It's not really a modified source bug. The bug is there regardless whether I modify it or not. In the very least the algorithm isn't working as advertised in this snippet. Considering that these samples have an encyclopedic role leaving it in there seems borderline irresponsible.

This call 
https://github.com/NVIDIA/cuda-samples/blob/6be514679b201c8a0f0cda050bc7c01c8cda32ec/Samples/reduction/reduction_kernel.cu#L594
will read out of bounds for size 1.

**Comment by mdoijade** [comment]
@emjotde  yes this needs to be investigated reopening. thanks for providing details.
just on a side note, size==1 is not good input for GPU.

**Comment by mdoijade** [comment]
This is fixed now on the tot, closing the issue.
