### ISSUE TITLE
NVJepg not support for 4 channels jpeg compress

### ISSUE THREAD

**Issue by gangdelian** [NVIDIA/cuda-samples#26]
I need to compress a image with RGBA four channels data, and send the compressed data to another pc from network.  libjpeg-turbo supports CMYK format to compress four channels data, but I have no idea how to use nvjpeg to compress a image with RGBA four channels data. Can someone help me?

**Comment by maheshkha** [comment]
Currently nvJPEG decoder supports CMYK formats - [nvJPEG decoder](https://docs.nvidia.com/cuda/nvjpeg/index.html#nvjpeg-decode-params-set-allow-cmyk)

But on nvJPEG encoder side RGB/BGR interleaved and non-interleaved supported, Planer YUV in chroma subsampling. 

Future release of nvJPEG encoder may have CMYK feature.

**Comment by gangdelian** [comment]
> Currently nvJPEG decoder supports CMYK formats - [nvJPEG decoder](https://docs.nvidia.com/cuda/nvjpeg/index.html#nvjpeg-decode-params-set-allow-cmyk)
> 
> But on nvJPEG encoder side RGB/BGR interleaved and non-interleaved supported, Planer YUV in chroma subsampling.
> 
> Future release of nvJPEG encoder may have CMYK feature.

Thanks, hope it will come soon
