### ISSUE TITLE
CUDA tested by nbody with errors

### ISSUE THREAD

**Issue by shizhuocaoa** [NVIDIA/cuda-samples#28]
I've installed cuda 10.1 for GeForce RTX 2080. But when I finished installing, I try to use nbody to test. There is an error presented by cudaErrorOperatingSystem:

**CUDA error at bodysystemcuda_impl.h:183 code=304(cudaErrorOperatingSystem) "cudaGraphicsGLRegisterBuffer(&m_pGRes[i], m_pbo[i], cudaGraphicsMapFlagsNone)"**

Can anyone help me solve this problem? Thank you!

**Comment by mdoijade** [comment]
@shizhuocaoa which OS you are running the nbody app on ? can you run other cuda apps on it ?

**Comment by mdoijade** [comment]
Closing as no response, assuming issue resolved.

**Comment by Etienne12345** [comment]
FYI, this happened to me when my monitor was plugged to the wrong graphics card (the one on the motherboard). Everything went fine after pluggin the monitor on the right GPU, and rebooting the machine. My setup was Centos7 with rtx-2080-ti.

**Comment by MJimitater** [comment]
Have the same problem.
Running Ubuntu 20.04., yes, I can run a hello-world cuda app

**Comment by acse-ogb119** [comment]
I get the same Problem using Windows Subsystem for Linux (WSL2). More details here https://forums.developer.nvidia.com/t/required-opengl-extensions-missing-code-304-cudaerroroperatingsystem-cudagraphicsglregisterbuffer/163525

**Comment by rambip** [comment]
Exact same problem:
I'm running on a laptop with a nvidia geforce card on linux (arch).
All the cuda examples work, opengl seems to run without bugs but this particular function gives me error code 999 (unknown)

**Comment by HaoLIU94** [comment]
Sloved it by using

__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia + (command)

for running graphical program <command> with off-loading.

Found from here https://forums.developer.nvidia.com/t/running-sample-gives-code-999-cudaerrorunknown-how-can-this-be-solved/128947/3

**Comment by ahmetyz** [comment]
In my case, I have two GPUs (one of them is an internal GPU) and my screen is plugged to the internal one. When I plugged my screen to the other one, error is vanished.

**Comment by antonmilev** [comment]
"In my case, I have two GPUs (one of them is an internal GPU) and my screen is plugged to the internal one. When I plugged my screen to the other one, error is vanished."

Can you please explain how exactly you did this?

**Comment by mfrasca60** [comment]
It happens to me as well but it is expected as I have a Tesla P40 in a Razor Core X and no graphic output is expected. The other graphic card is native Intel.
