### ISSUE TITLE
Support for tile_partition() of greater tile size?

### ISSUE THREAD

**Issue by jon-chuang** [NVIDIA/cuda-samples#29]
I am only able to get tile_partitions of size 32 or smaller. This seems unecessarily limiting. Why aren't tiles of greater size supported? I don't understand how syncing across threads_groups of size smaller than 32 makes sense since a warp of 32 threads is executed in lockstep. Shouldn't thread_groups be in multiples of 32 then?

Is there a way of partitioning a grid of blocks into different groups?

**Comment by mdoijade** [comment]
@jon-chuang 
Why aren't tiles of greater size supported?
--> cooperative groups only allow for now tile sizes upto 32. it is documented here - https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#tiled-partitions-cg

Shouldn't thread_groups be in multiples of 32 then? 
--> that support is currently not available in cuda, you can either syncwarp which is max 32 threads or __syncthreads() which is block wide.

Is there a way of partitioning a grid of blocks into different groups?
You can create only a single group which span across entire grid - https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#grid-synchronization-cg

**Comment by jon-chuang** [comment]
Does this mean that one can have different tiles within a warp executing different code now? I don't understand the purpose of tiling.

**Comment by ziyuhuang123** [comment]
> Does this mean that one can have different tiles within a warp executing different code now? I don't understand the purpose of tiling.

Agree. Seems meaningless!
