### ISSUE TITLE
Provide link to repo page to download binary

### ISSUE THREAD

**Issue by RangaSamudrala** [NVIDIA/cuda-samples#294]
README says - "Without using git the easiest way to use these samples is to download the zip file containing the current version by clicking the "Download ZIP" button on the repo page." 

So, where is the **repo page**? Please include link to repo page.

**Comment by LiquidPT** [comment]
I'm sure they mean the release page: https://github.com/NVIDIA/cuda-samples/releases

**Comment by LiquidPT** [comment]
Actually, they're referring to the main page of this repo. Click on the `Code` button and there's a `Download ZIP` link 

![Image](https://github.com/user-attachments/assets/95954594-7569-4913-80b0-ba92af06443c)

**Comment by RangaSamudrala** [comment]
Thanks.
