### ISSUE TITLE
compilation error for target  'bodysystemcuda.o'

### ISSUE THREAD

**Issue by sherkwast** [NVIDIA/cuda-samples#3]
After I installed cuda-10.0 , I tried to test the example "nobody". However it showed the followings,

> /usr/local/cuda-10.0/bin/nvcc -ccbin g++ -I../../common/inc  -m64    -ftz=true -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_75,code=compute_75 -o bodysystemcuda.o -c bodysystemcuda.cu
In file included from ../../common/inc/GL/freeglut.h:17:0,
                 from bodysystemcuda.cu:19:
../../common/inc/GL/freeglut_std.h:84:10: fatal error: GL/gl.h: No such file or directory
 #include <GL/gl.h>
          ^~~~~~~~~
compilation terminated.
Makefile:304: recipe for target 'bodysystemcuda.o' failed
make: *** [bodysystemcuda.o] Error 1

I am sure that I have already installed freeglut and related mesa packages, and reinstalling them did not work. How to solve it?

**Comment by mdoijade** [comment]
@sherkwast generally you can get GL headers from "mesa-common-dev" package. Have you tried installing it?
