### ISSUE TITLE
what's the difference between ce and sm mode ?

### ISSUE THREAD

**Issue by lilei461536135** [NVIDIA/cuda-samples#31]
what's the difference between CE and SM mode ?
what's the difference between cudamemcpyPeerAsync and copyp2p function ?

**Comment by mdoijade** [comment]
@lilei461536135 
--> CE is Copy Engine, hence copies performed by copy engine, this is achieved through cudaMemcpy/cudamemcpyPeerAsync  calls.
--> SM is Streaming Multiprocessor, hence copies performed by SM, this achieved via cuda kernel in case copyp2p function.

**Comment by lilei461536135** [comment]
Hi Mdoijade，
cudaMemcpy/cudamemcpyPeerAsync is performed by CPU, while copyp2p is performed by GPU. Right ?
