### ISSUE TITLE
cuda.h:791 code=100(cudaErrorNoDevice) "cudaGetDeviceCount(&device_count)" 

### ISSUE THREAD

**Issue by imSrbh** [NVIDIA/cuda-samples#34]
```
[Matrix Multiply Using CUDA] - Starting... 
CUDA error at ../../Common/helper_cuda.h:791 code=100(cudaErrorNoDevice) "cudaGetDeviceCount(&device_count)" 
```

**Comment by mdoijade** [comment]
@imSrbh there is some issue your driver installation. you can verify if you've installed driver correctly by running nvidia-smi.

**Comment by mpizzagalli777** [comment]
Hi. I am having the same issue. This is what nvidia-smi returns. Is something installed incorrectly @mdoijade ? 
![NVIDIA-smi](https://github.com/NVIDIA/cuda-samples/assets/154617296/ea2d63fa-e6ed-4643-9c12-4ebd1723cdde)

**Comment by bryanlinnan** [comment]
> Hi. I am having the same issue. This is what nvidia-smi returns. Is something installed incorrectly [@mdoijade](https://github.com/mdoijade) ? ![NVIDIA-smi](https://github.com/NVIDIA/cuda-samples/assets/154617296/ea2d63fa-e6ed-4643-9c12-4ebd1723cdde)

Hi , have you solved the problem?

**Comment by mpizzagalli777** [comment]
Hi, Its been so long I am not exactly sure what solved the issue but I believe I reinstalled all of the drivers from their website. Before doing that, try running apt get-update followed by apt get-upgrade. That has helped with some issues as well. Sorry I cannot be more helpful but it has been too long!
