### ISSUE TITLE
Cuda 10.0 debian package installs Cuda 10.2

### ISSUE THREAD

**Issue by ParikaGoel** [NVIDIA/cuda-samples#37]
I want to install Cuda 10.0 on my Ubuntu 18.04 system. I followed all the instructions mentioned on cuda official website
https://developer.nvidia.com/cuda-10.0-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=deblocal

But it installs 10.2 version.
![image](https://user-images.githubusercontent.com/35452780/81102074-5addfb00-8f0f-11ea-8865-489f5b99379d.png)

Could anyone please help me in this regard ?

**Comment by mdoijade** [comment]
please raise this issue in nvidia cuda developer forums this is a issue tracker for cuda samples.
