### ISSUE TITLE
Is cuHook still relevant in cuda 10.2?

### ISSUE THREAD

**Issue by hyc3z** [NVIDIA/cuda-samples#39]
I found cuHook samples on documentation pointing to cuda samples here:
https://docs.nvidia.com/cuda/cuda-samples/index.html#cuda-interception-library
But there seems to be no cuHook under sample directory.
Is api interception via LD_PRELOAD still working on cuda 10.2?

**Comment by mdoijade** [comment]
@hyc3z yes cuHook is still supported, it is present in samples which is part of cuda toolkit installer, only currently it is not in this github samples repo.
