### ISSUE TITLE
Examples with cublasDgetrfBatched

### ISSUE THREAD

**Issue by pguthrey** [NVIDIA/cuda-samples#42]
I couldn't find any examples of cublasDgetrfBatched/cublasDgetrsBatched.  

I am trying to use these with openmp to solve many small-to-medium sized matrices:
https://forums.developer.nvidia.com/t/openmp-cublas-for-batched-matrix-solves-using-lu/127265

I saw that there was a batched cholesky example
 https://docs.nvidia.com/cuda/cusolver/index.html#batchchol-example1
but I was unable to make similar code work for LU.

**Comment by Ru7w1k** [comment]
Please take a look at this sample: [simpleCUBLAS_LU](https://github.com/NVIDIA/cuda-samples/tree/master/Samples/simpleCUBLAS_LU)
(added in CUDA 11.3)
