### ISSUE TITLE
NVIDIA CUDA 11.0 RC CUDNN 8 Docker Tensorflow

### ISSUE THREAD

**Issue by vinhdiesal** [NVIDIA/cuda-samples#43]
I'm not sure which forum is appropriate for this. I downloaded the latest `docker image` from  NVIDIA NGC for NVIDIA/CUDA because it has the latest `CUDA 11.0 with CUDNN 8.0`. I also downloaded the latest `tensorflow-20.03-tf3-..` from NGC. 
My question is how do I configure this so that the tensorflow container looks for CUDA 11.0 and CUDNN 8.0 because right now it is looking for CUDA 10.02 and CUDNN 7. I thought maybe they created a compatible image because they updated it last week. 

Thanks,

**Comment by demizer** [comment]
Hello! The Nvidia Tensorflow container and the CUDA containers are two separate entities. If you want to use CUDA 11 with the Nvidia TF container, I would wait for the TF 20.06 container release. Hope that helps!
