### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_80'

### ISSUE THREAD

**Issue by GuanhuaWang** [NVIDIA/cuda-samples#44]
Hi I tried to run the sample code here in `~/cuda-samples/Samples/p2pBandwidthLatencyTest` on AWS g3 and p3 instance, with CUDA v10.0.130

When I try `make` it reports following errors:

```
ubuntu@ip-172-31-21-246:~/cuda-samples/Samples/p2pBandwidthLatencyTest$ make
/usr/local/cuda/bin/nvcc -ccbin g++ -I../../Common  -m64    -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_80,code=compute_80 -o p2pBandwidthLatencyTest.o -c p2pBandwidthLatencyTest.cu
nvcc fatal   : Unsupported gpu architecture 'compute_80'
Makefile:311: recipe for target 'p2pBandwidthLatencyTest.o' failed
make: *** [p2pBandwidthLatencyTest.o] Error 1
```

**Comment by mdoijade** [comment]
@GuanhuaWang you need to install cuda 11.0 toolkit to compile these samples. cuda 11.0 supports compute_80 (ampere arch GPU).

**Comment by udnaan** [comment]
The maintainers seem to tag each cuda requirement bump so depending on the cuda version you have, a simple thing to do is to do a `git checkout v11.0` and if you are like me and keep multiple cuda versions, do a `env CUDA_PATH=/usr/local/nvidia/cuda/11.0 make`

Replace 11.0 with the cuda version you have.

**Comment by h1z1** [comment]
Was about to report this again.  Why is that required on all samples including those that are not specific to that arch?  Nothing builds otherwise.

**Comment by jtillots** [comment]
You can remove the "80 86" from the SMS lines in the Makefiles. Then you can build it with Cuda10.

**Comment by mikizvi** [comment]
Similar issue with newb building the cuda-samples after a completely clean by-the-book latest-stable install on Ubuntu 22.04:
nvcc fatal   : Unsupported gpu architecture 'compute_89'

My fix was:
export SMS="50 52 60 61 70 75 80 86"
before running a "make -k" command.
