### ISSUE TITLE
unable to run cuda samples

### ISSUE THREAD

**Issue by lARSHADl** [NVIDIA/cuda-samples#47]
install cuda 

make[1]: Entering directory '/home/ahmed/cuda-samples/Samples/dmmaTensorCoreGemm'
>>> GCC Version is greater or equal to  5.0.0 <<<
/usr/local/cuda/bin/nvcc -ccbin g++ -I../../Common  -m64    --std=c++11 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_80,code=compute_80 -o dmmaTensorCoreGemm.o -c dmmaTensorCoreGemm.cu
make[1]: /usr/local/cuda/bin/nvcc: Command not found
make[1]: *** [Makefile:348: dmmaTensorCoreGemm.o] Error 127
make[1]: Leaving directory '/home/ahmed/cuda-samples/Samples/dmmaTensorCoreGemm'
make: *** [Makefile:45: Samples/dmmaTensorCoreGemm/Makefile.ph_build] Error 2

**Comment by mdoijade** [comment]
your cuda installation is may be missing /usr/local/cuda symlink or you haven't installed may you installation guide can help you https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
