### ISSUE TITLE
p2p samples crash GPUs

### ISSUE THREAD

**Issue by h1z1** [NVIDIA/cuda-samples#48]
Using different configurations of 3 1080TIs, with and without SLI, I'm able to reproduce a crash with the p2p samples.  

Tested:
> ./0_Simple/simpleP2P/simpleP2P
> ./1_Utilities/p2pBandwidthLatencyTest

GPUS:
-  EVGA 1080TI FTW3

NVIDIA Driver(s):
- several - kernel  confirmed upto 455.23.04
- cuda 10 and 11

Motherboard(s): 
-  Gigabyte X399 AORUS Gaming 7
-  ASUS X399 ROG Zenith Extreme

Though X becomes hosed, no errors are logged in syslog and the host remains responsive.  A running mpv process for example will continue outputting audio.

Attempts to reset the GPUs and/or unload the driver fail as does killing X (display goes black).

No issues with individual hardware though the driver and/or userland utilties like  nvidia-settings and nvidia-smi really do not play well with multi GPUs in Linux.

I'm  less concerned with the functionality and more that regular users are able to trigger it.

**Comment by mdoijade** [comment]
@h1z1 can you provide error with which these p2p samples are crashing?

**Comment by h1z1** [comment]
@mdoijade    That's the thing, there isn't.  Nothing logged in syslog nor output from the sample itself (it hangs).  It is quite reproducible if there's some other logging I can enable?

**Comment by mdoijade** [comment]
@h1z1 if you can share the "dmesg" log of post hang that should be helpful as well as you can run these samples with cuda-memcheck to see if there is any cuda API failure you are hitting.

**Comment by h1z1** [comment]
@mdoijade There's a lot of garbage logged in dmesg ..   I do see different XID events logged

```
Sep 21 09:59:59 runtime kernel: nvidia 0000:07:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0003 address=0x80000040 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:07:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0003 address=0x9e139068 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:07:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0003 address=0x800007c0 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:07:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0003 address=0x80001040 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:07:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0003 address=0x80000f40 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:07:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0003 address=0x800016c0 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:07:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0003 address=0x80002040 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:07:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0003 address=0x80001e40 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:07:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0003 address=0x800025c0 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:07:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0003 address=0x80003040 flags=0x0020]
Sep 21 09:59:59 runtime kernel: AMD-Vi: Event logged [IO_PAGE_FAULT device=07:00.0 domain=0x0003 address=0x80002d40 flags=0x0020]
Sep 21 09:59:59 runtime kernel: AMD-Vi: Event logged [IO_PAGE_FAULT device=07:00.0 domain=0x0003 address=0x800034c0 flags=0x0020]
Sep 21 09:59:59 runtime kernel: AMD-Vi: Event logged [IO_PAGE_FAULT device=07:00.0 domain=0x0003 address=0x80004040 flags=0x0020]
Sep 21 09:59:59 runtime kernel: AMD-Vi: Event logged [IO_PAGE_FAULT device=07:00.0 domain=0x0003 address=0x80003c40 flags=0x0020]
Sep 21 09:59:59 runtime kernel: AMD-Vi: Event logged [IO_PAGE_FAULT device=07:00.0 domain=0x0003 address=0x800043c0 flags=0x0020]
Sep 21 09:59:59 runtime kernel: AMD-Vi: Event logged [IO_PAGE_FAULT device=07:00.0 domain=0x0003 address=0x80005040 flags=0x0020]
Sep 21 09:59:59 runtime kernel: AMD-Vi: Event logged [IO_PAGE_FAULT device=07:00.0 domain=0x0003 address=0x80004b40 flags=0x0020]
Sep 21 09:59:59 runtime kernel: AMD-Vi: Event logged [IO_PAGE_FAULT device=07:00.0 domain=0x0003 address=0x800052c0 flags=0x0020]
Sep 21 09:59:59 runtime kernel: AMD-Vi: Event logged [IO_PAGE_FAULT device=07:00.0 domain=0x0003 address=0x80006040 flags=0x0020]
Sep 21 09:59:59 runtime kernel: AMD-Vi: Event logged [IO_PAGE_FAULT device=07:00.0 domain=0x0003 address=0x80005a40 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:43:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000c address=0xd8139068 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:43:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000c address=0xc0000040 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:43:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000c address=0xc00007c0 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:43:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000c address=0xc0001040 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:43:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000c address=0xc0000f40 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:43:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000c address=0xc00016c0 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:43:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000c address=0xc0002040 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:43:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000c address=0xc0001e40 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:43:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000c address=0xc00025c0 flags=0x0020]
Sep 21 09:59:59 runtime kernel: nvidia 0000:43:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000c address=0xc0003040 flags=0x0020]
Sep 21 10:00:01 runtime systemd: Started Session 8 of user root.
Sep 21 10:00:10 runtime kernel: NVRM: GPU at PCI:0000:43:00: GPU-redacted
Sep 21 10:00:10 runtime kernel: NVRM: GPU Board Serial Number: 
Sep 21 10:00:10 runtime kernel: NVRM: Xid (PCI:0000:43:00): 8, pid=45657, Channel 0000002b
Sep 21 10:01:01 runtime systemd: Started Session 9 of user root.
```

**Comment by h1z1** [comment]
Though the failures happen without any virtualization too, just occurred to me  IOMMU might be a cause given those cards would be in different IOMMU groups?

**Comment by mdoijade** [comment]
@h1z1 IOMMU is required for virtual machine cases, but it is required to be disabled for bare metal. P2P in such a case is unsupported behavior, anything can happen, hence the hang/crash.

**Comment by h1z1** [comment]
Not sure why this was closed, the crashes are reproducible outside VMs.   Unless the driver is intentionally configuring the hardware for isolation??  Why would the SLI bridge not be used?

**Comment by mdoijade** [comment]
CUDA Peer-to-Peer transaction do not use the SLI bridge. So presence of it should not matter.
And this was closed because it seems to me you are trying to run with IOMMU enabled for baremetal.

**Comment by h1z1** [comment]
> CUDA Peer-to-Peer transaction do not use the SLI bridge.

Fair enough, would it not be more advantageous to warn about that rather then crash?

> trying to run with IOMMU enabled for baremetal

Correct, at least it's enabled.  Still not quite following though, there's no VM involved.

**Comment by h1z1** [comment]
@mdoijade  I can confirm disabling IOMMU does allow those test to run.  I still don't think that should be acceptable though given IOMMU is enabled by default from vendors and the driver should be telling the hardware no?  Certainly a hard crash can't be acceptable to NVIDIA either.

Strange timing but GN also ran into some issues with two 3090's in SLI though didn't say what specifically didn't work besides PCIE fallback wasn't working.  https://www.youtube.com/watch?v=y4fb_R5Ogw0

**Comment by mdoijade** [comment]
@h1z1 Though this issue with IOMMU does not exist in windows platforms. I suggest to raise your concern regarding the driver behavior with IOMMU in NVIDIA Developer forum as this cuda samples repo issue tracker.

**Comment by h1z1** [comment]
Doesn't exist with AMD hardware either.  Funny you mention nvidia forums, this was apparently already reported.

https://forums.developer.nvidia.com/t/peer-to-peer-dma-transfers-bug-under-intel-vt-d-iommu-virtualization/47961

https://forums.developer.nvidia.com/t/simplep2p-example-and-multi-gpu-network-training-causes-system-freeze-and-err-in-nvidia-smi/70225/4

Regarding reporting here, the official samples from NVIDIA are able to crash their hardware, given people use these to confirm functionality and no doubt copy for their own use, it seemed prudent to at least document.   Could also be argued NVIDIA do their own validation.

We're talking about machines people spend many thousands if not 10's of thousands of dollars on.
