### ISSUE TITLE
results wrong when executing cuda-samples/Samples/cudaTensorCoreGemm

### ISSUE THREAD

**Issue by CodingYue** [NVIDIA/cuda-samples#5]
When testing the code with different configuration: "M=32, N = 16, K=64, M_TILES = N_TILES = K_TILES=1", and turn on the CPU_DEBUG option, result of `simple_wmma_gemm` mismatched.

Line 460:
should be 
``` c++
if (aRow < m_ld && aCol < k_ld && bRow < n_ld && bCol < k_ld) 
```
line 464,
should be
```c++
wmma::load_matrix_sync(a_frag, a + aCol + aRow * k_ld, k_ld);
```

**Comment by mdoijade** [comment]
Sample sources are meant to be consumed as is, any changes in input parameter can cause bug which is expected. Closing this issue.
