### ISSUE TITLE
make file error 

### ISSUE THREAD

**Issue by parth3153** [NVIDIA/cuda-samples#54]
when i sudo make i get this error:
nvcc fatal   : Unsupported gpu architecture 'compute_80'
Makefile:311: recipe for target 'bandwidthTest.o' failed
make[1]: *** [bandwidthTest.o] Error 1
make[1]: Leaving directory '/home/parth/cuda-samples/Samples/bandwidthTest'
Makefile:45: recipe for target 'Samples/bandwidthTest/Makefile.ph_build' failed
make: *** [Samples/bandwidthTest/Makefile.ph_build] Error 2

please help

**Comment by mdoijade** [comment]
seems that you are building v11.0 tag samples with cuda toolkit < 11.0, you need at least cuda toolkit 11.0 to get compute_80 support.

**Comment by mikizvi** [comment]
Similar issue with newb building the cuda-samples after a completely clean by-the-book latest-stable install on Ubuntu 22.04:
nvcc fatal   : Unsupported gpu architecture 'compute_89'

My fix was:
export SMS="50 52 60 61 70 75 80 86"
before running the make command.
