### ISSUE TITLE
calculation time and method used in npp box filter

### ISSUE THREAD

**Issue by YRstronger** [NVIDIA/cuda-samples#55]
hi, 
    i am start using cuda to do some image processing task. I am interested in the method implemented in npp box filter. Because i found it calculate too long (3ms, 1024*1024,radius 6) , but when i used seperate filter method provided in _Imaging/boxFilter, which only cost averagely 0.7ms to do the same thing,
    Is npp boxfilter not a seperate filter method? Or the texture use lead to the improvement?
    looking forward to answer！ thanks

**Comment by maheshkha** [comment]
Hi, 
Sample example _Imaging/boxFilter - used 2D filtering type.
You can explore the other NPP API to make the example separable filter capabilities [Column Filter](https://docs.nvidia.com/cuda/npp/group__image__filter__column.html) and [Row Filter](https://docs.nvidia.com/cuda/npp/group__image__filter__row.htmll).
Currently NPP API does not use Texture memory.

[NPP Image filter using Gaussian filter kernel](https://docs.nvidia.com/cuda/npp/group__image__filter__gauss.html)

Hope this will help.

**Comment by YRstronger** [comment]
thanks for your reply! that's exactly the difference of those two functions. 
I will close this issue soon!
