### ISSUE TITLE
Errors running make SMS="61" on Ubuntu 20.04

### ISSUE THREAD

**Issue by sephethus** [NVIDIA/cuda-samples#56]
Errors I'm getting on Ubuntu 20.04, GTX 1080

make SMS="61"

make[1]: Entering directory '/home/nate/cuda-samples-11.1/Samples/cudaNvSci'
>>> WARNING - libnvscibuf.so not found, please install libnvscibuf.so <<<
>>> WARNING - libnvscisync.so not found, please install libnvscisync.so <<<
>>> WARNING - nvscibuf.h not found, please install nvscibuf.h <<<
>>> WARNING - nvscisync.h not found, please install nvscisync.h <<<

I installed everything, here's my output for nvidia-smi

Fri Dec 11 09:35:27 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.38       Driver Version: 455.38       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   49C    P0    35W / 215W |    640MiB /  8116MiB |     11%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1380      G   /usr/lib/xorg/Xorg                 53MiB |
|    0   N/A  N/A      3036      G   /usr/lib/xorg/Xorg                309MiB |
|    0   N/A  N/A      3163      G   /usr/bin/gnome-shell               64MiB |
|    0   N/A  N/A      3847      G   ...AAAAAAAAA= --shared-files       16MiB |
|    0   N/A  N/A      4960      G   ...AAAAAAAA== --shared-files       82MiB |
|    0   N/A  N/A      8021      G   ...AAAAAAAAA= --shared-files        9MiB |
|    0   N/A  N/A      8509      G   ...AAAAAAAA== --shared-files       34MiB |
|    0   N/A  N/A     11138      G   gnome-control-center                1MiB |
|    0   N/A  N/A     11459      G   /opt/zoom/zoom                     51MiB |
+-----------------------------------------------------------------------------+

CUDA_SEARCH_PATH=/usr/lib/x86_64-linux-gnu

Not finding a good answer on this anywhere for modern times in 2020.

**Comment by mdoijade** [comment]
cudaNvSci currently only works with automotive cuda releases, as the cudaNvSci sample makefile is emitting warning so you can discard it.
you can get more details about NvSci in this comment - https://github.com/NVIDIA/cuda-samples/issues/22#issuecomment-562105202
