### ISSUE TITLE
make error: nvcc fatal   : Unknown option '--threads'

### ISSUE THREAD

**Issue by nbaldy** [NVIDIA/cuda-samples#57]
I was following the instructions in this post: https://weblogs.asp.net/dixin/setup-and-use-cuda-and-tensorflow-in-windows-subsystem-for-linux-2 and got to the step of downloading/making this repository, I just used the master branch. 
Error: 
```
/usr/local/cuda/bin/nvcc -ccbin g++ -I../../Common  -m64    --threads 0 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_86,code=compute_86 -o concurrentKernels.o -c concurrentKernels.cu
nvcc fatal   : Unknown option '--threads'
make: *** [Makefile:323: concurrentKernels.o] Error 1
```

Checking out Tag v11.2 had the same result, checking out Tag v11.1 looks like it worked with some warnings:
```
/usr/local/cuda/bin/nvcc -ccbin g++ -I../../Common  -m64    -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_86,code=compute_86 -o concurrentKernels.o -c concurrentKernels.cu
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/local/cuda/bin/nvcc -ccbin g++   -m64      -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_86,code=compute_86 -o concurrentKernels concurrentKernels.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
mkdir -p ../../bin/x86_64/linux/release
cp concurrentKernels ../../bin/x86_64/linux/release
```

I just wanted to make people aware of it & how to get something to build in case they're also trying something similar. (And so that it can be fixed if it's a bug). Thanks!

**Comment by BDHU** [comment]
I encountered the same error. Not sure if newer versions of nvcc solves the issue.

**Comment by mdoijade** [comment]
--threads is nvcc compiler option introduced in cuda 11.2 toolkit, so please use tag v11.1 samples if you are using cuda 11.1 toolkit.

**Comment by jeff-yajun-liu** [comment]
what is the fix? I have a similar issue on Ubuntu 18.04 and trying to run those with A100 GPU, here is the error message: /usr/local/cuda/bin/nvcc -ccbin g++ -I../../Common  -m64    --threads 0 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_86,code=compute_86 -o p2pBandwidthLatencyTest.o -c p2pBandwidthLatencyTest.cu
nvcc fatal   : Unknown option '--threads'
Makefile:323: recipe for target 'p2pBandwidthLatencyTest.o' failed
make: *** [p2pBandwidthLatencyTest.o] Error 1

**Comment by ahmetserdar** [comment]
I have no idea.

**Comment by mdoijade** [comment]
the fix is to use cuda 11.2 toolkit, this compiler option "--threads" got introduced from the toolkit version 11.2.
else you can use samples tagged with v11.1 where the makefiles doesn't have this option in it.

**Comment by BDHU** [comment]
Or you can remove the "--threads" from the Makefile for now.

**Comment by watmough** [comment]
For building the samples when you make have multiple CUDA toolkits installed, and wish to build with a particular toolkit and `nvcc`, you can define `CUDA_PATH` inline with the `make` command. Example, to build the CUDA 11.3 samples on my work laptop, I can do:
```
CUDA_PATH=/usr/local/cuda-11.3 make
```
