### ISSUE TITLE
Cuda-8.0 sample aarch64 platform error

### ISSUE THREAD

**Issue by tv12345** [NVIDIA/cuda-samples#6]
Hello, I am unable to make the samples folder for aarch64 platform using the command 
make TARGET_ARCH=aarch64
 Errors I encounter :- 

aarch64-linux-gnu-g++  -o simpleAssert_nvrtc simpleAssert.o  -lcuda -lnvrtc
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: cannot find -lcuda
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: cannot find -lnvrtc

**Comment by mdoijade** [comment]
have you installed cuda cross compilation toolkit? looks like you have not.
Please find the instructions in this link to install aarch64 linux cuda toolkit bits - https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#cross-platform
