### ISSUE TITLE
Is there working cuda toolkit version for cuda-sample/Samples other than 10.0

### ISSUE THREAD

**Issue by Sungwoo-Ahn** [NVIDIA/cuda-samples#7]
I'm trying to execute cuda-samples using CUDA-9.0. 
But it says samples' prerequisites are CUDA 10.0

Is it impossible to make it working it with CUDA-9.0?
The thing is... my work is about trying to run on gpgpu-sim which provides CUDA-9.0
However I get this error for every application in cuda-samples. (version libcudart.so.9.0 not found). 
But it does exist at location where it says not found. Below shows existance at that location.
![image](https://user-images.githubusercontent.com/26740096/53395877-57371600-39e6-11e9-82a8-12d1922cb39e.png)
  
The below is results from running samples.
![image](https://user-images.githubusercontent.com/26740096/53395678-c5c7a400-39e5-11e9-95ea-48fee5529f87.png)
![image](https://user-images.githubusercontent.com/26740096/53395779-0a533f80-39e6-11e9-9134-9a5223049a23.png)

ANY kinds of help would be helpful.

Thank you
Sungwoo Ahn

**Comment by mdoijade** [comment]
@Sungwoo-Ahn 
samples like matrixMul/shfl_scan which does not require cuda 10.0 specific features can be compiled and run with cuda 9.0 toolkit.
It seems that you have not set LD_LIBRARY_PATH to your cuda 9.0 libcudart.so location, have you set it?

**Comment by Sungwoo-Ahn** [comment]
> @Sungwoo-Ahn
> samples like matrixMul/shfl_scan which does not require cuda 10.0 specific features can be compiled and run with cuda 9.0 toolkit.
> It seems that you have not set LD_LIBRARY_PATH to your cuda 9.0 libcudart.so location, have you set it?

**Comment by Sungwoo-Ahn** [comment]
Sorry about closing. I'm first time using Issue here.

@mdoijade 
I already set LD_LIBRARY_PATH to my cuda/lib64 location. 
![image](https://user-images.githubusercontent.com/26740096/53457463-d9bae680-3a75-11e9-9bcd-5b68def875fc.png)
But it still shows same error. Still working on it.

When you say it's okay to use CUDA 9.0 on non cuda 10.0 features, does it mean it's okay to use samples applications that use tensor cores which appear on Volta architecture? I think cuda 10.0's specific features are using RT cores or DLSS.
