### ISSUE TITLE
Reporting couple of bugs in cdpQuadtree

### ISSUE THREAD

**Issue by SaumyadipM** [NVIDIA/cuda-samples#72]
hi

A couple of issues to report in CUDA samples - \v11.2\6_Advanced\cdpQuadtree

1. Children offsets in lines 544-547 in the kernel build_quadtree_kernel are incorrect. They should be changed to:
children[child_offset + 0].set_id(4 * node.id() + 0);
children[child_offset + 1].set_id(4 * node.id() + 1);
children[child_offset + 2].set_id(4 * node.id() + 2);
children[child_offset + 3].set_id(4 * node.id() + 3);
2. Tree traversal routine incorrectly is looking for children in a leaf node of the tree in function (line 586 in check_quadtree). It should be changed to:
if (!(params.depth == params.max_depth || num_points <= params.min_points_per_node))

thanks

**Comment by Ru7w1k** [comment]
added these changes in cdpQuadtree sample.

Thank you!
