### ISSUE TITLE
Multiple two large numbers as strings and return result

### ISSUE THREAD

**Issue by creberger** [NVIDIA/cuda-samples#8]
//First attempt. Feel free to speed it up.

#include <stdio.h>
#define array_size 200

__global__
void collatz(char *mult1, char *mult2, char *cresult)
{
	int sizea,sizeb,i,j ;
	char a[array_size] ={0};
	char b[array_size] ={0};
	int result[array_size] ={0};

	sizea= 0; while ( *(mult1+sizea) != '\0') {a[sizea] = *(mult1+sizea) ; sizea++ ;}
	sizeb= 0; while ( *(mult2+sizeb) != '\0') {b[sizeb] = *(mult2+sizeb) ; sizeb++ ;} // i and j are now size of the string array

	 for( i = sizea - 1; i >= 0; i-- )
	 	{
	 		for( j = sizeb - 1; j >= 0; j-- )
	 		{
	 			result[ i + j + 1 ] += (b[j]-'0')*(a[i]-'0'); // thanks: https://www.quora.com/How-do-I-multiply-two-large-numbers-stored-as-strings-in-the-C-C++-language
	 		}

	 	}
	 	for(  i = sizea + sizeb; i >= 0; i-- ){
	 		if( result[ i ] >= 10 ){
	 			result[ i - 1 ] +=result[ i ] / 10;
	 			result[ i ] %= 10;
	 		}
	 	}

	 	for( i = 0; i < (sizea + sizeb); i++ ){
	 		cresult[i] = result[i]+'0' ;
	 	}

	 	return ;
}

int main(void)
{
char *x, *y, *z ;
	cudaMallocManaged(&x, array_size*sizeof(char));
	cudaMallocManaged(&y, array_size*sizeof(char));
	cudaMallocManaged(&z, array_size*sizeof(char));

	strcpy(x,"92937842347899823492793849823489");
	strcpy(y,"3239478293345989359873457898489");
	strcpy(z,"0");

	collatz<<<1, 1>>>(x,y,z) ;

	cudaDeviceSynchronize();

    printf("%s times %s = %s",x,y,z);

  // Free memory
  cudaFree(x);
  cudaFree(y);
  cudaFree(z);

  return 0;
}

**Comment by mdoijade** [comment]
We appreciate your interest in contribute to cuda samples project, for now github cuda samples are not open for public contributions, we may open to it future you can check updates about it here - https://github.com/NVIDIA/cuda-samples#contributors-guide
