### ISSUE TITLE
Link to "Accelerated Computing Blog" in README.md is dead

### ISSUE THREAD

**Issue by leosh64** [NVIDIA/cuda-samples#82]
The [References](https://github.com/NVIDIA/cuda-samples/blob/master/README.md#references) section of the `README.md` file contains a dead link to https://devblogs.nvidia.com/category/accelerated-computing/ (shows 404).

Has the category moved or was it renamed? Maybe the link can be updated.

**Comment by Ru7w1k** [comment]
Fixed in [11.5](https://github.com/NVIDIA/cuda-samples/releases/tag/v11.5).
