### ISSUE TITLE
Typo in matrixMul note message

### ISSUE THREAD

**Issue by zois-tasoulas** [NVIDIA/cuda-samples#84]
There is a space missing after the word "performance", [matrixMul.cu](https://github.com/NVIDIA/cuda-samples/blob/master/Samples/matrixMul/matrixMul.cu#L281)

As it is right now, the message on the terminal appears as "performancemeasurements".

**Comment by Ru7w1k** [comment]
Fixed in [11.5](https://github.com/NVIDIA/cuda-samples/releases/tag/v11.5).
