### ISSUE TITLE
Missing samples

### ISSUE THREAD

**Issue by zzzoom** [NVIDIA/cuda-samples#9]
Are there any plans to add the rest of the samples that come with CUDA? NPP-related samples have a few bugs I wanted to send PRs for.

**Comment by mdoijade** [comment]
NPP samples shall be added in near future though not sure of specific time period of it.
Appreciate your interest in fixing the bugs in it, for now github cuda samples are not open for public contributions, we may open to it future you can check updates about it here - https://github.com/NVIDIA/cuda-samples#contributors-guide
